version: 0.0
os: linux

files:
  - source: httpd/app.conf
    destination: /etc/httpd/conf.d/
  - source: dist/public/
    destination: /appdata/app/public/

permissions:
  - object: /appdata/
    pattern: "**"
    except:
    owner: apache
    group: apache
    mode: 700
    type:
      - directory
      - file

hooks:
  BeforeInstall:
     - location: scripts/beforeinstall.sh
       timeout: 5
       runas: root
  AfterInstall:
    - location: scripts/afterinstall.sh
      timeout: 5
      runas: root
  ApplicationStart:
    - location: scripts/start.sh
      timeout: 10
      runas: root
  ApplicationStop:
    - location: scripts/stop.sh
      timeout: 30
      runas: root
  ValidateService:
    - location: scripts/validate.sh
      timeout: 5
      runas: root

